from unittest import TestCase


class TestTest(TestCase):
    def test_func(self):
        self.fail()
